apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "dist-mnist-for-e2e-test"
  annotations: {"kube-queue": "pending"}
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tf-dist-mnist-test:1.0
              resources:
                requests:
                  cpu: 2
                  memory: 2Gi
                limits:
                  cpu: 2
                  memory: 2Gi

    Worker:
      replicas: 4
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tfkub-dist-mnist-test:1.0
              resources:
                requests:
                  cpu: 2
                  memory: 2Gi
                limits:
                  cpu: 2
                  memory: 2Gi
